# values for staging 
# write here value will override the default values.yaml

replicaCount: 1
image:
  tag: "staging"
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# use for helm case test
testResponse: "Hello, World From Staging Env"